import useSWR from 'swr';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import runGraphQlQuery from '../services/run-graphql-query';
import ServiceList from '../components/ServiceList';

export default function Home() {
    const {data: serviceResponse, error} = useSWR('{ services { name } }', runGraphQlQuery);

    if (error) {
        console.log(error);
        return <div>Failed to load</div>;
    }
    if (!serviceResponse) {
        return <div>Loading...</div>;
    }

    const {services} = serviceResponse;

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                Hello world

                <ServiceList services={services}/>
            </main>
        </div>
    );
}
