import useSWR from 'swr';
import type {NextPage} from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
    const {data, error} = useSWR('{ users { name } }', fetcher);

    if (error) return <div>Failed to load</div>;
    if (!data) return <div>Loading...</div>;

    const {users} = data;

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                Hello world

                <div>
                    {users.map((user: { name: string }, i: number) => (
                        <div key={i}>{user.name}</div>
                    ))}
                </div>
            </main>
        </div>
    );
};


const fetcher = (query: object) =>
    fetch('/api/graphql', {
        method: 'POST',
        headers: {
            'Content-type': 'application/json',
        },
        body: JSON.stringify({query}),
    })
        .then((res) => res.json())
        .then((json) => json.data);

export default Home;
